[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --force && php -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
