@php $currentRoute = Route::currentRouteName(); @endphp
<div class="flex gap-2 overflow-x-auto mb-6" style="-ms-overflow-style:none;scrollbar-width:none;">
    <a href="{{ route('seller.dashboard') }}"     class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.dashboard'     ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-gauge-high"></i> Dashboard</a>
    <a href="{{ route('seller.billing') }}"       class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.billing'       ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-file-invoice-dollar"></i> Billing</a>
    <a href="{{ route('seller.schedule') }}"      class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.schedule'      ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-calendar-days"></i> Schedule</a>
    <a href="{{ route('seller.reviews') }}"       class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.reviews'       ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-star"></i> Reviews</a>
    <a href="{{ route('seller.notifications') }}" class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.notifications' ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-bell"></i> Notifications</a>
    <a href="{{ route('seller.affiliate') }}"     class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.affiliate'     ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-link"></i> Affiliate</a>
    <a href="{{ route('seller.settings') }}"      class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.settings'      ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-gear"></i> Settings</a>
    <a href="{{ route('seller.onboarding') }}"    class="shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition {{ $currentRoute==='seller.onboarding'    ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-600' }}"><i class="fa-solid fa-user-pen"></i> Profile</a>
</div>
